config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get 'pages/about'
  get 'feedbacks', to: 'feedback#new'
  post 'feedbacks', to: 'feedback#create'
  resources :articles
  resources :users, except: [:new]
  resources :categories
  resource :two_factor_settings, except: %i[show]
end

app/models/article.rb
# frozen_string_literal: true

class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 3000 }
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  has_rich_text :description
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def edit; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully.'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = 'Article was deleted successfully.'
    else
      flash[:alert] = 'Something went wrong, please try again.'
    end

    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    return unless current_user != @article.user && !current_user.admin?

    flash[:alert] = 'You can only edit or delete your own article'
    redirect_to @article
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <%= link_to article.user.username, user_path(article.user)%>
          <%if article.categories.any? %>
            <div class="mt-2">
              <%= render  article.categories%>
            </div>
          <%end%>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
          <p class="card-text line-clamp"><%= truncate(strip_tags(article.description.to_s), length: 150) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
          <% if current_user && (article.user == current_user || current_user.admin?)%>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= button_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <%end%>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago,
          Last updated <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/articles/_error_display.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
     <div class="col-20">
       <%= render 'shared/error_display', obj: @article%>
       <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
         <div class="form-group row">
           <%= f.label :title, class: "col-2 col-form-label text-light" %>
           <div class="col-10">
             <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
           </div>
         </div> <br>
         <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10 row-12">
            <%= f.rich_textarea :description, rows: 12, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div><br />
        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
      </div>
    <% end %>
  </div>
  <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create A New Article</h1>

<%= render 'form'%>

<p><%#= link_to("Cancel and go to listing of all Articles",articles_path)%> </p>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username%>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <%if @article.categories.any? %>
            <div class="mt-2">
              <%= render  @article.categories%>
            </div>
          <%end%>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= @article.description %></div>
          <% if current_user && (@article.user == current_user || current_user.admin? )%>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= button_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <%end%>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
          Last updated <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>