config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get 'pages/about'
  get 'feedbacks', to: 'feedback#new'
  post 'feedbacks', to: 'feedback#create'
  resources :articles
  resources :users, except: [:new]
  resources :categories
  resource :two_factor_settings, except: %i[show]
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 15 }
  validates :name, uniqueness: true
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update show destroy]
  before_action :should_admin, only: %i[new create edit update destroy]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category created successfully'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category updated successfully'
      redirect_to @category
    else
      flash.now[:alert] = 'Something went wrong please try again later'
      render 'new'
    end
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    if @category.destroy
      flash[:success] = 'Category deleted successfully'
      redirect_to categories_path
    else
      flash.now[:alert] = 'Something went wrong please try again later'
      redirect_to @category
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def should_admin
    return if current_user&.admin?

    flash[:alert] = 'Only admin can create category'
    redirect_to categories_path
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_categories.html.erb
<div class="container">
<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-6 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to category.name, category_path(category), class: "text-success" %>
            <p class="card-text mt-3">
              <%= pluralize(category.articles.count, "article") %>
            </p>
          </h5>
        </div>
        <% if current_user && current_user.admin? %>
          <p class="card-text">
            <%= link_to "Edit category", edit_category_path(category), class: "btn btn-outline-info" %>
            <%= link_to "Delete category", category_path(category), class: "btn btn-outline-danger", method: :delete %>
          </p>
        <%end%>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(category.created_at) %> ago,
          Updated <%= time_ago_in_words(category.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category) , class: 'badge badge-pill badge-success btn btn-success'%>

app/views/categories/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
     <div class="col-10">
       <%= render 'shared/error_display', obj: @category%>
       <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
         <div class="form-group row">
           <%= f.label :name, 'Category name', class: "col-2 col-form-label text-light" %>
           <div class="col-10">
             <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
           </div>
         </div>
        <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
      </div>
    <% end %>
  </div>
  <%= link_to '[ Cancel and return to category listing ]', categories_path, class: "text-info" %>
</div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">EDIT THE CATEGORY</h1>

<%= render 'form'%>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing all categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<%= render 'categories' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">CREATE NEW CATEGORY</h1>

<%= render 'form'%>

app/views/categories/show.html.erb
<h2 class="text-center mt-4"><%= @category.name %></h2>

<% if current_user && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>