config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get 'pages/about'
  get 'feedbacks', to: 'feedback#new'
  post 'feedbacks', to: 'feedback#create'
  resources :articles
  resources :users, except: [:new]
  resources :categories
  resource :two_factor_settings, except: %i[show]
end

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "alert" ? "danger" : "success" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
      <small>Copyright &copy; Anurag Mishra.All Rights Reserved </small>
    <% if current_user %>
      | <small><%= link_to 'Feedback About Website', feedbacks_path, class: 'text-green' %></small>
    <%end%>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <%= link_to 'Blogs', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <li> <%= link_to 'Articles', articles_path, class: 'nav-link' %></li>

      <li> <%= link_to 'Categories', categories_path, class: 'nav-link' %>
      <% if current_user %>
        <li><%= link_to('New Article', new_article_path, class: 'nav-link') %></li>

        <li> <%= link_to('New Category', new_category_path, class: 'nav-link') if current_user.admin? %></li>

        <li> <%= link_to 'Edit your details', edit_user_registration_path(current_user), class: 'nav-link' %></li>
        <li> <%= link_to('Profile', current_user, class: 'nav-link') %></li>

        <li> <%= button_to 'Log out', destroy_user_session_path, class: 'nav-link btn btn-danger d-flex', 'method': :delete %></li>
      <% else %>
        <li> <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %></li>
        <li> <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar'%>
    <div id="page-content">
      <%= render 'layouts/flash_messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>